# Generated by Django 5.2.17 on 2026-08-18 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='is_custom',
            field=models.BooleanField(default=False, help_text='Designates whether this topic was created by a user.'),
        ),
    ]
