# Generated by Django 5.2.17 on 2026-08-18 19:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_topic_is_custom'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='essay',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User who wrote this essay (null for anonymous/guest submissions).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='essays', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='topic',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User who created this topic (null for AI/system default topics).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topics', to=settings.AUTH_USER_MODEL),
        ),
    ]
